### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by webcane** [webcane/webcane.github.io#15]
подумать о том, как оптимизировать временные параметры для анимации.
Возможно использовать скрипт для этого

```html
<a href="#about" title="open site" class="letters_wave"> 
						<span id="word_1">
							<span class="d3 animated bounceInUp">c</span>
							<span class="d2 animated bounceInUp">a</span>
							<span class="d6 animated bounceInUp">n</span>
							<span class="d1 animated bounceInUp">e</span>
						</span>
						<span id="word_2">
							<span class="d9 animated bounceInUp">o</span>
							<span class="d4 animated bounceInUp">n</span>
						</span>
						<span id="word_3">
							<span class="d2 animated bounceInUp">g</span>
							<span class="d10 animated bounceInUp">i</span>
							<span class="d7 animated bounceInUp">t</span>
							<span class="d3 animated bounceInUp">h</span>
							<span class="d5 animated bounceInUp">u</span>
							<span class="d8 animated bounceInUp">b</span>
						</span> 
						<span id="word_4"> 
							<span class="d7 animated bounceInUp">p</span>
							<span class="d9 animated bounceInUp">a</span>
							<span class="d3 animated bounceInUp">g</span>
							<span class="d6 animated bounceInUp">e</span>
							<span class="d10 animated bounceInUp">s</span>
						</span> 
						<!-- <span class="icon-chevron-down"></span> -->
					</a>
```

и 
```css
/* ____________________ ANIMATIONS ____________________ */

.d1  { animation-delay:0.2s; -moz-animation-delay:0.2s; -webkit-animation-delay:0.2s; }
.d2  { animation-delay:0.3s; -moz-animation-delay:0.3s; -webkit-animation-delay:0.3s; }
.d3  { animation-delay:0.4s; -moz-animation-delay:0.4s; -webkit-animation-delay:0.4s; }
.d4  { animation-delay:0.5s; -moz-animation-delay:0.5s; -webkit-animation-delay:0.5s; }
.d5  { animation-delay:0.6s; -moz-animation-delay:0.6s; -webkit-animation-delay:0.6s; }
.d5  { animation-delay:0.8s; -moz-animation-delay:0.8s; -webkit-animation-delay:0.8s; }
.d7  { animation-delay:0.9s; -moz-animation-delay:0.9s; -webkit-animation-delay:0.9s; }
.d8  { animation-delay:  1s; -moz-animation-delay:  1s; -webkit-animation-delay:  1s; }
.d9  { animation-delay:1.2s; -moz-animation-delay:1.2s; -webkit-animation-delay:1.2s; }
.d10 { animation-delay:1.4s; -moz-animation-delay:1.4s; -webkit-animation-delay:1.4s; }
.d11 { animation-delay:1.5s; -moz-animation-delay:1.5s; -webkit-animation-delay:1.5s; }
```
